### ISSUE TITLE
Normalize flags and config params

### ISSUE THREAD

**Issue by illya13** [cosmos/ethermint-archive#31]

**Comment by ramilexe** [comment]
@illya13 could you provide more details about this issue? Take a look to https://github.com/tendermint/ethermint/pull/54

**Comment by illya13** [comment]
- the idea was to review `go-ethereum` and `tendermint` features
- have list of features we want to keep / disable
- review config parameters and flags to control selected features

**Comment by adrianbrink** [comment]
- [x] Log Level / Verbosity flag - #54 
- [x] decide which ```go-ethereum``` to include in ```ethermint``` - #32 
- [x] standardise config parameters and flags between ```go-ethereum```, ```ethermint```, ```tendermint``` and ```basecoin``` - #32

**Comment by adrianbrink** [comment]
@illya13 Do you want to keep this one open or close it in favour of #32?

**Comment by illya13** [comment]
@adrianbrink I'm more interested in some `vision` how do we merge 2 frameworks
and `roadmap` based on that. Taking that into an account I'm more interested in #32

**Comment by ebuchman** [comment]
Ok - some of this is addressed by https://github.com/tendermint/ethermint/issues/77. Also added an architecture overview in https://github.com/tendermint/ethermint/blob/develop/ARCHITECTURE.md. Closing this in favour of those and more to come
